services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v26.2.1
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - '1'
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --node-id
      - '0'
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://localhost:9092
    ports:
      - '9092:9092'
